const projectData = [
  {
    title: 'SpeedQuiz',
    text: 'This site facilitates a charades type game, intended for English students.  Students are given a list of words and they must help their teammates guess as many words as possible within a time limit, without saying the word.',
    image: 'speedquiz_thumbnail',
    video: 'speedquiz',
    link: 'https://speedquiz.classpoint.ca',
    git: 'https://github.com/booklvr/speedQuiz',
    tags: [
      'Html5',
      'Sass',
      'Bootstrap',
      'React',
      'Redux',
      'Axios',
      'JSON Webtokens',
      'NodeJs',
      'Express',
      'MongoDB',
      'NGinx',
    ],
  },
  {
    title: 'Classpoint',
    text: 'Classpoint helps teachers to keep track of their students points for classroom games.  Classlists are saved, and games can be set up as individual games, team games, or boys vs girls.',
    image: 'classpoint_thumbnail',
    video: 'classpoint',
    link: 'https://classpoint.ca',
    git: 'https://github.com/booklvr/class_point2',
    tags: [
      'Pug',
      'Sass',
      'ES6',
      'NodeJs',
      'Express',
      'MongoDB',
      'Babel',
      'Parcel',
      'Axios',
      'Passport',
      'Google OAuth2',
      'NGinx',
    ],
  },
  {
    title: 'Scategories',
    text: 'Scategories is a creative-thinking category-based game.  The objective is to score points by uniquely naming objects within a set of categories, given an initial letter, within a time limit.',
    image: 'scategories_thumbnail',
    video: 'scategories',
    link: 'https://scategories.classpoint.ca',
    git: 'https://github.com/booklvr/scategories-esl',
    tags: ['HTML5', 'Sass', 'Bootstrap', 'React', 'Redux', 'Babel', 'Parcel'],
  },
  {
    title: 'ConnectFour',
    text: 'This site uses connect four, a game where opponents must connect 4 of their tiles in a row by dropping them down columns.  It is adapted as a tool to teach English as students must call out some target language to choose their column.',
    image: 'connectfour_thumbnail',
    video: 'connectfour',
    link: 'https://connectfour.classpoint.ca',
    git: 'https://github.com/booklvr/connectFour',
    tags: [
      'Pug',
      'Sass',
      'Bootstrap',
      'ES6',
      'Express',
      'MongoDB',
      'Cloudinary',
      'Multer',
      'Passport',
      'Google OAuth2',
      'Parcel',
      'Babel',
      'NGinx',
    ],
  },
]

export default projectData
